export const ACTIONS_TYPE_API_SPLASH = {
	_INTIAL_REQUEST: '_INTIAL_REQUEST',
	_SUCCESS_REQUEST_: '_SUCCESS_REQUEST_',
	_ERORR_REQUEST: '_ERORR_REQUEST',
	_SET_QUERY: '_SET_QUERY',
	_SET_PAGE_PHOTOS: '_SET_PAGE',
	_SET_PAGE_COLLECTIONS: '_SET_PAGE_COLLECTIONS',
	_SET_PAGE_USERS: '_SET_PAGE_USERS',
	_SET_PER_PAGE_PHOTOS: '_SET_PER_PAGE_PHOTOS',
	_SET_PER_PAGE_COLLECTIONS: '_SET_PER_PAGE_COLLECTIONS',
	_SET_PER_PAGE_USERS: '_SET_PER_PAGE_USERS',
	_SET_ORDER_BY_PHOTOS: '_SET_ORDER_BY_PHOTOS',
};
