export const ACTIONS_COLLECTION = {
	_INIT_REQUEST_COLLECTION_: '_INIT_REQUEST_COLLECTION_',
	_SUCCESS_REQUEST_COLLECTION_: '_SUCCESS_REQUEST_COLLECTION_',
	_FAILURE_REQUEST_COLLECTION_: '_FAILURE_REQUEST_COLLECTION_',
	_SET_ID_COLLECTION_: '_SET_ID_COLLECTION_',
};
