export const ACTIONS_COLLECTIONS = {
	_INIT_REQUEST_COLLECTIONS_: '_INIT_REQUEST_COLLECTIONS_',
	_SUCCESS_REQUEST_COLLECTIONS_: '_SUCCESS_REQUEST_COLLECTIONS_',
	_FAILURE_REQUEST_COLLECTIONS_: '_FAILURE_REQUEST_COLLECTIONS_',
	_SET_PAGE_COLLECTIONS_: '_INCREMENT_PAGE_COLLECTIONS_',
	_SET_PER_PAGE_COLLECTIONS_: '_SET_PER_PAGE_COLLECTIONS_',
	_SET_QUERY_COLLECTIONS_: '_SET_QUERY_COLLECTIONS_',
};
