export const ACTIONS_PHOTOS = {
	_INIT_REQUEST_PHOTOS_: '_INIT_REQUEST_PHOTOS_',
	_SUCCESS_REQUEST_PHOTOS_: '_SUCCESS_REQUEST_PHOTOS_',
	_FAILURE_REQUEST_PHOTOS_: '_FAILURE_REQUEST_PHOTOS_',
	_SET_PAGE_PHOTOS_: '_INCREMENT_PAGE_PHOTOS_',
	_SET_PER_PAGE_PHOTOS_: '_SET_PER_PAGE_PHOTOS_',
	_SET_ORDER_BY_PHOTOS_: '_SET_ORDER_BY_PHOTOS_',
	_SET_QUERY_PHOTOS_: '_SET_QUERY_PHOTOS_',
};
