export interface IActionsUsers {
	_INIT_REQUEST_USERS_: string;
	_SUCCESS_REQUEST_USERS_: string;
	_FAILURE_REQUEST_USERS_: string;
	_SET_PER_PAGE_USERS_: string;
	_SET_PAGE_USERS_: string;
	_SET_QUERY_USERS_: string;
}

export const ACTIONS_USERS: IActionsUsers = {
	_INIT_REQUEST_USERS_: 'INIT_REQUEST_USER_',
	_SUCCESS_REQUEST_USERS_: 'SUCCESS_REQUEST_USER_',
	_FAILURE_REQUEST_USERS_: 'FAILURE_REQUEST_USER_',
	_SET_PER_PAGE_USERS_: 'SET_PER_PAGE_',
	_SET_PAGE_USERS_: 'SET_PAGE_',
	_SET_QUERY_USERS_: 'SET_QUERY_',
};
