export const ACTIONS_USER = {
	_INIT_REQUEST_USER_: '_INIT_REQUEST_',
	_SUCCESS_REQUEST_USER_: '_SUCCESS_REQUEST_',
	_FAILURE_REQUEST_USER_: '_FAILURE_REQUEST_',
	_SET_PER_PAGE_PHOTOS_USER_: '_SET_PER_PAGE_PHOTOS_',
	_SET_ORDER_BY_PHOTOS_USER_: '_SET_ORDER_BY_PHOTOS_',
};
