export const COLORS_THEME = {
	DARK: {
		_PRIMARY_: '#746CFE',
		_SECONDARY_: '#ffffff',
		_TERTIARY_: '#3071e7',
		_BG_: '#010202',
		_BLACK_: '#000000',
	},
	LIGHT: {
		_PRIMARY_: '#000000',
		_SECONDARY_: '#7868E6',
		_CYAN_: '#a6b2ec',
		_BG_: '#F9F3EE',
		_BLUR_: '#ffeeff73',
		_WHITE_: '#ffffff',
	},
	_NAV_: '#080c25',
	_NAV_LIGHT_: '#242132',
	_GRAY_: '#161e35',
	_BLUE_: '#3071e7',
	_WHITE_: '#fff',
	_BLACK_: '#010202',
	_CYAN_: '#a6b2ec',
	_PURPLE_: '#746cfe',
	_PURPLE_300: '#9c8ffc',
	_PURPLE_LIGHT_: '#ae8cfa',
};

export const colors = {
	navTheme: {
		500: COLORS_THEME._NAV_,
	},
	navLightTheme: {
		500: COLORS_THEME._NAV_LIGHT_,
	},
	grayTheme: {
		500: COLORS_THEME._GRAY_,
	},
	blueTheme: {
		500: COLORS_THEME._BLUE_,
	},
	whiteTheme: {
		500: COLORS_THEME._WHITE_,
	},
	blackTheme: {
		500: COLORS_THEME._BLACK_,
	},
	cyanTheme: {
		500: COLORS_THEME._CYAN_,
	},
	bgTheme: {
		500: COLORS_THEME._NAV_LIGHT_,
	},
	purpleTheme: {
		200: COLORS_THEME._PURPLE_300,
		300: COLORS_THEME._PURPLE_300,
		500: COLORS_THEME._PURPLE_,
		600: COLORS_THEME._PURPLE_,
	},
	primaryDark: {
		200: COLORS_THEME.DARK._PRIMARY_,
		300: COLORS_THEME.DARK._PRIMARY_,
		500: COLORS_THEME.DARK._PRIMARY_,
		600: COLORS_THEME.DARK._PRIMARY_,
	},
	secondaryDark: {
		200: COLORS_THEME.DARK._SECONDARY_,
		300: COLORS_THEME.DARK._SECONDARY_,
		500: COLORS_THEME.DARK._SECONDARY_,
		600: COLORS_THEME.DARK._SECONDARY_,
	},
	tertiaryDark: {
		200: COLORS_THEME.DARK._TERTIARY_,
		300: COLORS_THEME.DARK._TERTIARY_,
		500: COLORS_THEME.DARK._TERTIARY_,
		600: COLORS_THEME.DARK._TERTIARY_,
	},
	bgDark: {
		200: COLORS_THEME.DARK._BG_,
		300: COLORS_THEME.DARK._BG_,
		500: COLORS_THEME.DARK._BG_,
		600: COLORS_THEME.DARK._BG_,
	},
	blackDark: {
		200: COLORS_THEME.DARK._BLACK_,
		300: COLORS_THEME.DARK._BLACK_,
		500: COLORS_THEME.DARK._BLACK_,
		600: COLORS_THEME.DARK._BLACK_,
	},
	primaryLight: {
		200: COLORS_THEME.LIGHT._PRIMARY_,
		300: COLORS_THEME.LIGHT._PRIMARY_,
		500: COLORS_THEME.LIGHT._PRIMARY_,
		600: COLORS_THEME.LIGHT._PRIMARY_,
	},
	secondaryLight: {
		200: COLORS_THEME.LIGHT._SECONDARY_,
		300: COLORS_THEME.LIGHT._SECONDARY_,
		500: COLORS_THEME.LIGHT._SECONDARY_,
		600: COLORS_THEME.LIGHT._SECONDARY_,
	},

	cyanLight: {
		200: COLORS_THEME.LIGHT._CYAN_,
		300: COLORS_THEME.LIGHT._CYAN_,
		500: COLORS_THEME.LIGHT._CYAN_,
		600: COLORS_THEME.LIGHT._CYAN_,
	},
	bgLight: {
		200: COLORS_THEME.LIGHT._BG_,
		300: COLORS_THEME.LIGHT._BG_,
		500: COLORS_THEME.LIGHT._BG_,
		600: COLORS_THEME.LIGHT._BG_,
	},
	blurLight: {
		200: COLORS_THEME.LIGHT._BLUR_,
		300: COLORS_THEME.LIGHT._BLUR_,
		500: COLORS_THEME.LIGHT._BLUR_,
		600: COLORS_THEME.LIGHT._BLUR_,
	},
	whiteLight: {
		200: COLORS_THEME.LIGHT._WHITE_,
		300: COLORS_THEME.LIGHT._WHITE_,
		500: COLORS_THEME.LIGHT._WHITE_,
		600: COLORS_THEME.LIGHT._WHITE_,
	},
};
export const fonts = {
	body: `Poppins, sans-serif`,
	heading: `Poppins, sans-serif`,
};
